ceph-volume-scenario: pin the tox version
Due to a regression introduced in tox 4.3.1, we have to pin
the version used in the CI in order to avoid the following error:

```
tox.report.HandledError: replace failed in centos8-filestore-create.commands with MatchRecursionError('circular chain between set env VAGRANT_UP_FLAGS, CEPH_DEV_BRANCH, CEPH_DEV_SHA1')
```

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>