builder.yaml: Install iproute2
Test scripts like qa/tasks/cephfs/mount.py expect the ip command to be
available in the container environment. Without it, tests fail with:

```
  /bin/bash: line 1: ip: command not found

  File "/ceph/qa/tasks/cephfs/mount.py", line 96, in cleanup_stale_netnses_and_bridge
    p = remote.run(args=['ip', 'netns', 'list'],
  ...
  teuthology.exceptions.CommandFailedError: Command failed with status 127: 'ip netns list'
```
Add the iproute2 package to Ubuntu/Debian package list to make sure this
package is installed.

See also 6b144aa7dd8495664115a5b31f31151ca66ea062, which installs
the locales package.

Signed-off-by: Kefu Chai <k.chai@proxmox.com>