build: fix unkown option
Newer version of pip does not support --download anymore, the option has
been replaced by --cache-dir.
This fixes errors like:

+ /tmp/venv.ufvIkiZl8v/bin/pip download
--dest=/home/jenkins-build/.cache/pip pip
ERROR: unknown command "download"

Signed-off-by: Sébastien Han <seb@redhat.com>