scripts/build_utils.sh: dyna link against libgcc when building crimson
as seastar requires dynamic linkage of libgcc, see the comment for more
details. see also

https://github.com/scylladb/seastar/blob/master/src/core/exception_hacks.cc

without this change, we will have errors like:

/usr/lib/gcc/x86_64-linux-gnu/9/libgcc_eh.a(unwind-dw2.o): In function
`_Unwind_RaiseException':
(.text+0x24b0): multiple definition of `_Unwind_RaiseException'
../../../lib/libseastar.a(exception_hacks.cc.o):./obj-x86_64-linux-gnu/src/seastar/./src/seastar/include/seastar/core/future.hh:738:
first defined here
collect2: error: ld returned 1 exit status
src/test/crimson/CMakeFiles/unittest_seastar_lru.dir/build.make:140:
recipe for target 'bin/unittest_seastar_lru' failed

Signed-off-by: Kefu Chai <kchai@redhat.com>