kernel: install perl
perl has been required for building the Linux kernel for a long time
but it's not installed explicitly.

  error: Failed build dependencies:
  	perl is needed by kernel-7.1.0_g0248d0a325dc-1.x86_64
  make[2]: *** [scripts/Makefile.package:75: binrpm-pkg] Error 11

Signed-off-by: Ilya Dryomov <idryomov@gmail.com>