ceph-dev-pipeline: Still send with_crimson=true
The replacement of crimson builds with debug builds is still half baked.  ceph.spec and install-deps are still expecting with_crimson to be set if the crimson dependency packages should be installed.

See https://github.com/ceph/ceph/blame/main/ceph.spec.in#L367-L384 for the dependencies that will never get installed.

This is manifesting in:
```
+ rpmbuild --rebuild '-D_topdir /ceph/rpmbuild' --with=sccache --without=dwz --with=tcmalloc /ceph/ceph-20.3.0-4645.gcfa448da.el9.src.rpm
error: Failed build dependencies:
	cryptopp-devel is needed by ceph-2:20.3.0-4645.gcfa448da.el9.x86_64
	gcc-toolset-13-gcc-plugin-annobin is needed by ceph-2:20.3.0-4645.gcfa448da.el9.x86_64
	gcc-toolset-13-libasan-devel is needed by ceph-2:20.3.0-4645.gcfa448da.el9.x86_64
	gcc-toolset-13-libubsan-devel is needed by ceph-2:20.3.0-4645.gcfa448da.el9.x86_64
	gnutls-devel is needed by ceph-2:20.3.0-4645.gcfa448da.el9.x86_64
	hwloc-devel is needed by ceph-2:20.3.0-4645.gcfa448da.el9.x86_64
	libasan is needed by ceph-2:20.3.0-4645.gcfa448da.el9.x86_64
	libpciaccess-devel is needed by ceph-2:20.3.0-4645.gcfa448da.el9.x86_64
	libubsan is needed by ceph-2:20.3.0-4645.gcfa448da.el9.x86_64
	lksctp-tools-devel is needed by ceph-2:20.3.0-4645.gcfa448da.el9.x86_64
	ragel is needed by ceph-2:20.3.0-4645.gcfa448da.el9.x86_64
Installing /ceph/ceph-20.3.0-4645.gcfa448da.el9.src.rpm
2025-12-22 17:48:10,148: INFO: step done: rpm failed in 00:00:27
```

Nothing will ever tell build-with-container.py or install-deps.sh to pull those dependencies in because we're no longer setting WITH_CRIMSON due to this removal https://github.com/ceph/ceph-build/commit/0f0e4fd7dea0c06d855b93581e5b13cc0bf4c350#diff-d34216471695ce2f36f9cf1550524392c85b94d0566b3bc6d591383411b91f25R218-L381.

Signed-off-by: David Galloway <david.galloway@ibm.com>